[package]
name = "RfeedMultibot"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio_schedule = "0.3.2"
tokio = { version = "1.41.1", features = ["rt", "rt-multi-thread", "macros"] }
chrono = "0.4.38"
bsky-sdk = "0.1.12"