version: '3.8'

services:
  rfeedbot:
    image: rfeed-bot-image:latest
    restart: unless-stopped
    volumes:
      - rfeed-bot-data:/data
    environment:
      BSKY_USER: your-bsky-user
      BSKY_PASS: your-bsky-app-pass
      TG_TOKEN: your-telegra-token
      TG_CHANNEL: telegram-id-as-number
      DATADIR: /data

volumes:
  rfeed-bot-data: